field.formatter.settings.youtube_video_formatter:
  type: mapping
  label: Youtube Video formatter settings
  mapping:
    width:
      type: string
      label: Width
    height:
      type: string
      label: Height
